"""payments table

The Payment model (app/db/models.py) shipped with the Razorpay
integration, but no migration ever created its table. Nothing caught it
because app/db/session.py runs Base.metadata.create_all() for SQLite
only: local development and the whole test suite build every table
straight from the models, so `payments` was always present there.
Postgres has no such fallback and is driven purely by these migrations,
so on a real deployment the table simply did not exist and every billing
route failed with

    psycopg2.errors.UndefinedTable: relation "payments" does not exist

taking out POST /payments/create-order, /payments/verify and
/payments/webhook -- the whole paid-upgrade flow. The webhook case is the
worst of the three: Razorpay retries a 500, so a real captured payment
would be retried against a table that cannot exist.

Revision ID: 725a0947a57f
Revises: 50e6aac07088
Create Date: 2026-09-10 10:02:04.910600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725a0947a57f'
down_revision: Union[str, Sequence[str], None] = '50e6aac07088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'payments',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('tier', sa.String(), nullable=False),
        sa.Column('billing_cycle', sa.String(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('razorpay_order_id', sa.String(), nullable=False),
        sa.Column('razorpay_payment_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)

    # NOTE: `alembic revision --autogenerate` also emitted
    #     op.drop_column('resumes', 'embedding')
    # here, and it has been deliberately removed rather than kept.
    # `resumes.embedding` is a pgvector `vector(384)` column declared in
    # infra/schema.sql and migration e2c91358026a, intentionally OUTSIDE
    # models.py so this codebase has no hard dependency on the pgvector
    # Python package (see models.py's comment on that column). Autogenerate
    # compares the live schema against the models, sees a column the
    # metadata does not know about, and concludes it was deleted -- the
    # same reason reflecting that table logs
    # "SAWarning: Did not recognize type 'vector'".
    #
    # Applying it would silently drop every stored embedding. env.py now
    # excludes this column from autogenerate comparison so the next person
    # running --autogenerate does not get handed the same loaded gun.


def downgrade() -> None:
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_table('payments')
    # The autogenerated counterpart to the dropped op.drop_column above --
    # op.add_column('resumes', sa.Column('embedding', sa.NullType(), ...)) --
    # is omitted for the same reason. It would also have failed on its own
    # terms: sa.NullType() has no DDL representation to emit.
